name: plg_portfolio
description: Pablo L. Guerra's web-app portfolio powered by Flutter.
publish_to: "none"
version: 2.0.4+24

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  photo_view: ^0.14.0
  provider: ^6.0.5
  url_launcher: ^6.1.14
  intl: ^0.18.1
  chewie: ^1.7.1
  video_player: ^2.7.2
  youtube_player_iframe: ^4.0.4
  go_router: ^11.1.2
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/home/
    - assets/images/social/
    - assets/images/personal/
    - assets/images/professional/atlantic_insurance/
    - assets/images/professional/ambots/
    - assets/images/professional/am3_lab/
