name: plg_portfolio
description: Pablo L. Guerra's web-app portfolio powered by Flutter.
publish_to: "none"
version: 2.6.1+61

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  photo_view: ^0.14.0
  provider: ^6.1.2
  url_launcher: ^6.2.5
  intl: ^0.19.0
  chewie: ^1.8.3
  video_player: ^2.8.3
  youtube_player_iframe: ^4.0.4
  go_router: ^14.2.3
  url_strategy: ^0.2.0
  unorm_dart: ^0.3.0
  shimmer: ^3.0.0
  image_network: ^2.5.6
  animated_text_kit: ^4.2.2
  pinch_zoom: ^2.0.0
  flutter_spinkit: ^5.2.1
  package_info_plus: ^8.0.2
  flutter_tilt: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/json/
    - assets/images/home/
    - assets/images/icons/
    - assets/images/professional/atlantic_insurance/
    - assets/images/professional/ambots/
    - assets/images/professional/am3_lab/
    - assets/images/personal/mobile_sim_wheel/
    - assets/images/personal/amg_gt3_wheel/
    - assets/images/personal/android_calculator/
    - assets/images/personal/apple_charging_station/
    - assets/images/personal/f1_sim_engineer/
    - assets/images/personal/handroid/
    - assets/images/personal/led_wall_decor/
    - assets/images/personal/macro_pad/
    - assets/images/personal/project_lemans/
    - assets/images/personal/safedrive_mk1/
    - assets/images/personal/switch_speaker/
    - assets/images/personal/xbox_head_tracking/
    - assets/images/personal/flutter_resume_builder/
    - assets/images/personal/blokus/
    - assets/images/personal/swe_632_lottery/
